---
version: "3.9"
services:
  apache:
    build: .
#    image: docker.io/bitnami/apache:2.4
 #   ports:
  #    - 80:8080
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - apache
    ports:
      - 3000:3000
