- hosts: lb
  tasks:
  - name: "installing Loadbalancer software"
    package:
            name: "haproxy"
  - name: "copying haproxy configure file"
    template:
            dest: "/etc/haproxy/haproxy.cfg"
            src: "/home/kanav/Desktop/haproxy.cfg.j2"
  - command: "haproxy -f /etc/haproxy/haproxy.cfg"
