---
- name: Running MYSQL Database as Docker Container using Ansible.
  hosts: docker_servers
  remote_user: docker
  become: true


  vars:
    db_volume: db_data


  tasks:

  - name: Launch mysql database container
    docker_container:
      name: db_container
      image: mysql:5.7
      volumes:
        - "{{ db_volume }}:/var/lib/mysql"
      restart: true
      env:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: test
        MYSQL_USER: moodle
        MYSQL_PASSWORD: moodle
      ports:
        - "33060:3306"
